### ISSUE TITLE
Modify information 1044

### ISSUE THREAD

**Issue by a1991car** [filecoin-project/Allocator-Registry#10]
We fil the allocation_bookkeeping": "https://github.com/a1991car", This is wrong.
I need to change the address to "https://github.com/a1991car/Allocator-Public-Data".
Thanks

**Comment by a1991car** [comment]
@galen-mcandrew @Kevin-FF-USA , in this https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1044.json, we need to change the “allocation_bookkeeping": 
Put  the "https://github.com/a1991car" change to“https://github.com/a1991car/Allocator-Public-Data“

**Comment by Kevin-FF-USA** [comment]
Hi @a1991car,
Thanks for coming to the Governance call this week.   Have updated the bookkeeping address to now reflect this change.
