### ISSUE TITLE
Always sign failed（hope change the sign address ）

### ISSUE THREAD

**Issue by Chuangshi1** [filecoin-project/Allocator-Registry#12]
Dear:
We are Genesis, and i need your help. This is our application https://github.com/filecoin-project/notary-governance/issues/1019
There are two addresses in our ledger :
f1ldkhvk55psquvhc727udmdl2tgm55exndh2meqa and f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
we didn't create the multsign.
I offer f1ldkhvk55psquvhc727udmdl2tgm55exndh2meqa to you for V5 allocator in the #1019. But when i test allocator sign, it only show picture like this . The ledger can't identify  allocator signer address.
![image](https://github.com/filecoin-project/Allocator-Registry/assets/112937825/1869f3ad-60f6-430f-9d36-cbf78853ea41)
Maybe something wrong with my ledger. It can't show f1ldkhvk55psquvhc727udmdl2tgm55exndh2meqa address when i sign.
When we use other ledger with the 3rd address sign, it will show the 3rd address.
So hope change our signer address. Hope to change the address to this one: f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
Thank you so much. @galen-mcandrew

**Comment by Chuangshi1** [comment]
It can only show 5 addresses.It need to show all the Ledger address。

**Comment by Kevin-FF-USA** [comment]
Hi @Chuangshi1,
Thanks for raising this.  Just wanted to let you know we are working on a solution.  Will reply back shortly with update

**Comment by galen-mcandrew** [comment]
I think this is related to this issue: https://github.com/fidlabs/allocator-tooling/issues/10 , which has been resolved. Asking for an update.

**Comment by kevzak** [comment]
@Chuangshi1 follow these instructions and add a different f1 address to your multisig

https://docs.google.com/document/d/1eKnZNETVL9MH5btQgY9BfWEuvKXDdeop96EdqJ_9ymE/edit

**Comment by Chuangshi1** [comment]
![image](https://github.com/filecoin-project/Allocator-Registry/assets/112937825/63c778a6-aca1-4caf-a83e-f5cdafc60a9e)
@galen-mcandrew @Kevin-FF-USA @kevzak 
I connect with my ledger. It shows like this. It can't recognise the signer address. But the signer address actually in this ledger. 
Hope you can help us to add the new address. f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
Thank you so much.

**Comment by Chuangshi1** [comment]
@galen-mcandrew  f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
 Hope you can help us to add the new accounts.

**Comment by galen-mcandrew** [comment]
Added this address to the msig (https://filfox.info/en/address/f2m4ljkbqkw4rljq7mhu2xmdchnvbcuwqox4hebnq)

Also merged PR https://github.com/filecoin-project/Allocator-Registry/pull/23 

Should be resolved, closing for now. If there is still an error, please open a new PR/Issue. Thank you!
