### ISSUE TITLE
Change Github Account for 1034

### ISSUE THREAD

**Issue by ipfsforcezuofu** [filecoin-project/Allocator-Registry#126]
### Organization

IPFSForce

### Applicaiton Number

1034

### Updated Github

ipfsforcezuofu

### Would you like to

Modify an existing Github Handle

### Is the Github Account used to file this request is already recorded on the Allocator JSON for your organization?

No

### Additional Information

It was suggested by Kacper Żuk in the conversion with Jimmy at 6:05pm On July 12.

**Comment by ipfsforcezuofu** [comment]
The github_handles in https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1034.json is ["0x5459"]

**Comment by Kevin-FF-USA** [comment]
Hi @ipfsforcezuofu,

Just saw your note in SLACK.  Thanks for the ping - and apologies for the wait,  I thought this was good to go.  

So to clarify, the GITHUB handle ipfsforcezuofu ---IS NOT--- zuofu@kunyaokeji.com.

Would you like to have BOTH Github accounts connected to this Allocator, or modify to just ipfsforcezuofu?

**Comment by ipfsforcezuofu** [comment]
Hi @Kevin-FF-USA,

**Comment by Kevin-FF-USA** [comment]
Awesome!
Thanks @ipfsforcezuofu  - you're all set.  Apologies for the delay,  please let me know if there is anything else
https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1034.json
