### ISSUE TITLE
change github handle

### ISSUE THREAD

**Issue by FilscanOfficial** [filecoin-project/Allocator-Registry#127]
### Organization

filscan.io

### Applicaiton Number

1033

### Updated Github

FilscanOfficial

### Would you like to

Modify an existing Github Handle

### Is the Github Account used to file this request is already recorded on the Allocator JSON for your organization?

No

### Additional Information

The github handles attached to filscan's allocator is : "remakeZK",which is not correct. Please change it to user name--FilscanOfficial. Thank you so much!

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1033.json
