### ISSUE TITLE
Venus VFDA Pathway Address Modification

### ISSUE THREAD

**Issue by VenusOfficial** [filecoin-project/Allocator-Registry#128]
### Organization

Venus

### Applicaiton Number

https://github.com/filecoin-project/notary-governance/issues/1035

### Would you like to

Change an existing Multisig Address

### Previous address

f1mkeafrmvg3tiuugtcwpyumjbuyeoey3t2exa4ba

### New address

f1wzmrjlhu244jyjlpsjlyhp7en35ue4wpwbfsv3y

### Do you need Foundation Governance support to create the Multisig?

Yes

### Is the Github Account used to file this request is already recorded on the Allocator JSON for your organization?

Yes

### Additional Information

thank you

**Comment by VenusOfficial** [comment]
hi sir @Kevin-FF-USA , may I ask if there has been any progress about this?

**Comment by Kevin-FF-USA** [comment]
<img width="552" alt="image" src="https://github.com/user-attachments/assets/a84653db-c69a-4e93-8c3c-f365d92880d4">

Hi @VenusOfficial - this change to the signer should be all set.  Thanks for your patience.

**Comment by Kevin-FF-USA** [comment]
Hi @VenusOfficial,

Received the note in SLACK that this Multisig wasnt working for you.  Wanted to check in as we start to troubleshoot,  do you no longer have access to the original Ledger setup for this Allocator?

Asking because if you do - it can be much similar to add another signer vs changing the multisig - which can cause complications (like you may be experiencing now)

**Comment by VenusOfficial** [comment]
Hi @Kevin-FF-USA Thank you for your support!
The original ledger is personally owned, and according to our organization's new policy, it should be replaced by one owned by the organization. While I currently have access to the original ledger, there's no guarantee this will continue. To simplify the process, as you suggested, we are open to adding the new address from the organization's ledger while keeping the original ledger in the multisig, unless it's possible to operate the allocator without access to the original ledger.

**Comment by VenusOfficial** [comment]
Hi @Kevin-FF-USA 
The original Ledger is inaccessible now because its owner left the company last week. Could you please expedite the setup of the new one to ensure the continuation of DC services for our clients? Thank you.

**Comment by galen-mcandrew** [comment]
https://github.com/filecoin-project/Allocator-Registry/blob/81a722d3ea77a28a943b6256563e53102bb79b68/Allocators/1035.json#L3

f2 msig: f2hxivxs3we5afsuyx32lwwn44evopz7yea2fsmhy
Adding: f1wzmrjlhu244jyjlpsjlyhp7en35ue4wpwbfsv3y
Removing: f1mkeafrmvg3tiuugtcwpyumjbuyeoey3t2exa4ba

https://filfox.info/en/message/bafy2bzacecmo2a5hgjalzxf7srhzzrowpngzf66nbmxx3g6b2ispgu3tnk5ja
https://filfox.info/en/message/bafy2bzaceclj2b7oyiaikjhnu2odmly4eg65zrbppn2erw2rxah67vbn3uvoo
