### ISSUE TITLE
Request to remove the remaining datacap

### ISSUE THREAD

**Issue by Lind111** [filecoin-project/Allocator-Registry#14]
没有按照自己设置的流程操作，参考：https://github.com/Lind111/EF/issues/4

使用以下钱包删除剩余的datacap
f1266w3mjcy6vvzv22nclpk5xcttk6p43hkavywlq

**Comment by Kevin-FF-USA** [comment]
Hi @Lind111,
Working on this request now.  Will reply back when completed for you.

**Comment by galen-mcandrew** [comment]
Removed: https://datacapstats.io/clients?filter=f1266w3mjcy6vvzv22nclpk5xcttk6p43hkavywlq
