### ISSUE TITLE
Allocator application

### ISSUE THREAD

**Issue by lyjmry** [filecoin-project/Allocator-Registry#145]
### Allocator Pathway Name

Liong Labs

### Organization Name

Liong Labs

### Region of Operation

Asia minus Greater China Region

### Country your Organizaiton is based in

Singapore

### If you have previously applied or served as an Allocator/Notary, please provide the url to your past application(s)

N/A

### Type of Allocator and RFA List

RFA, Automated Github

### Existing OnChain Address

None

### Please confirm that you understand that in addition to submitting this Github issue, you will need to complete and submit the Airtable [Form](https://airtable.com)

(No)

### Please confirm that you have read and understand the Fil+ guidelines and your role as an Allocator

(Yes)
```[tasklist]
### Tasks
```

**Comment by lyjmry** [comment]
Hello @Kevin-FF-USA  I don't see any comments about Airtable.

**Comment by Kevin-FF-USA** [comment]
Hi @lyjmry,
I believe the reason you arent seeing the Airtable is the way this issue was created.
Rather than a Pull request it was opened as an issue.   Recommend you check out the steps that FIDL created, outlined in this article here. 

https://blog.allocator.tech/2024/05/rolling-applications-are-open-for.html

**Comment by Kevin-FF-USA** [comment]
Hi @lyjmry,
Havent heard back - but still here if you have any questions.  

Currently dont see a new application filed in the Allocator-Governance.  If you would like any support, please feel free to DM me in SLACK Kevin-Foundation, or come to one of the Governance calls for live support. 

Calendar invite:https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles

Times: 
![image](https://github.com/user-attachments/assets/6d0c023e-5631-407a-86d8-909911e3d0f7)
