### ISSUE TITLE
Oula Fil+ Datacap Allocator (OFDA)

### ISSUE THREAD

**Issue by AlexIbrahim859** [filecoin-project/Allocator-Registry#155]
### Allocator Pathway Name

Oula Fil+ Datacap Allocator (OFDA)

### Organization Name

Oula Team

### Region of Operation

Asia minus Greater China Region

### Country your Organizaiton is based in

Singapore

### Type of Allocator and RFA List

Market Based, Novel Pathway

### Existing OnChain Address

I have an existing f2 address already setup

### Please confirm that you understand that in addition to submitting this Github issue, you will need to complete and submit the Airtable [Form](https://airtable.com)

(Yes)

### Please confirm that you have read and understand the Fil+ guidelines and your role as an Allocator

(Yes)

**Comment by Kevin-FF-USA** [comment]
Hi @AlexIbrahim859 ,

Thanks for submitting this application and welcome to the community.  I wanted to send a friendly check in - dont see any information for the organization Oula in the Airtable (with completed application).

just wanted to confirm you were able to follow the steps in https://blog.allocator.tech/2024/05/rolling-applications-are-open-for.html

**Comment by AlexIbrahim859** [comment]
Hi @Kevin-FF-USA,

Thanks for the warm welcome! I’ve followed the steps provided in the link and successfully submitted the application. You can find the details here: [(https://github.com/filecoin-project/Allocator-Governance/issues/133)].

Thank you.

**Comment by Kevin-FF-USA** [comment]
Closing this issue out - please see https://github.com/https://github.com/filecoin-project/Allocator-Governance/issues/133 for application
