### ISSUE TITLE
Change allocation_bookkeeping adress

### ISSUE THREAD

**Issue by NewHuoPool** [filecoin-project/Allocator-Registry#16]
Allocator Pathway Number:
1040
Allocator Pathway Name:
NewHuoPool
Change Request:
change allocation_bookkeeping adress
from  "https://github.com/filplus-bookkeeping/NewHuoPool"  to  "https://github.com/NewHuoPool/NewHuoPoolPathway"

**Comment by Kevin-FF-USA** [comment]
Hi @NewHuoPool,
Thanks for this issue.   The JSON has been updated to reflect the new bookkeeping repo url

<img width="673" alt="image" src="https://github.com/filecoin-project/Allocator-Registry/assets/94004586/b9cfe31b-a6da-4669-a1d1-cbf279e239d3">
