### ISSUE TITLE
Request to update Github handles of MinerDAO

### ISSUE THREAD

**Issue by maxvint** [filecoin-project/Allocator-Registry#161]
### Organization

MinerDAO

### Applicaiton Number

1065

### Updated Github

maxvint

### Would you like to

Modify an existing Github Handle

### Is the Github Account used to file this request is already recorded on the Allocator JSON for your organization?

Yes

### Additional Information

My Github handles is maxvint, currently is Carohere, made a mistake when submitting it.
More details: https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1065.json.
The PR is https://github.com/filecoin-project/Allocator-Registry/pull/162.

**Comment by Kevin-FF-USA** [comment]
Hi @maxvint,
Github handles have been updated - REMOVED Carohere - Added maxvint.
In the separate issue you should see updates on the multisig change.
