### ISSUE TITLE
Request to change account for Allocator Data Preparer

### ISSUE THREAD

**Issue by Filedrive-OPS** [filecoin-project/Allocator-Registry#169]
### Organization

FileDrive Labs

### Applicaiton Number

1030

### Updated Github

laurarenpanda

### Would you like to

Modify an existing Github Handle

### Is the Github Account used to file this request is already recorded on the Allocator JSON for your organization?

No

### Additional Information

Hello,
Laurarenpanda, a member of Filedrive Lab, recently left the organization. Her responsibilities for the allocator (https://github.com/filecoin-project/notary-governance/issues/1030) have been transferred to me. I'm reaching out to request assistance with the transition. To demonstrate the relationship between the allocator, the organization, and myself, I have attached a screenshot of the repositories listed in question 47 of allocator 1030, along with the organization's team member list. The new GitHub account for the allocator is Filedrive-OPS, and the new signer is f1hhfjedejpwi44wffdqrs3xl6bnygzfjfj3tzpaq. Could you kindly let me know if there's anything else you need to initiate the transfer process? Thank you.
![图片](https://github.com/user-attachments/assets/94e6c339-1a62-4ca8-9f0b-23c2bebcce87)
![图片](https://github.com/user-attachments/assets/1454b4c6-cfb8-495f-80ca-bdcba66d4560)

**Comment by Kevin-FF-USA** [comment]
Hi @Filedrive-OPS ,

To confirm - you still have control of the ledger?

**Comment by Kevin-FF-USA** [comment]
Is the user:  "github_user": "laurarenpanda" still with the company?  Able to comment on the issue to give approval?

**Comment by laurarenpanda** [comment]
I confirm that the GitHub account and address for the allocator (filecoin-project/notary-governance#1030) can be transferred to @Filedrive-OPS .
Thank you.

**Comment by Filedrive-OPS** [comment]
@laurarenpanda Thank you for confirming!

@Kevin-FF-USA Could you please update the account and Ledger address as requested? Thank you.

**Comment by galen-mcandrew** [comment]
@Filedrive-OPS & @laurarenpanda 

Are you requesting that we **add signer** (f1hhfjedejpwi44wffdqrs3xl6bnygzfjfj3tzpaq) and **remove previous signer** (f1vewqfhde62bjccdiy3qbjbhg37ldr4y7nm5wv6q) from the **existing multisig** (https://filfox.info/en/address/f2n2cvq3wi344zua7ofax4jygkcqb4lwbhdtofhmq)?

OR is there another issue with the Ledger and multisig?

**Comment by Filedrive-OPS** [comment]
@galen-mcandrew 

Yes, we are requesting to replace the previous signer (f1vewqfhde62bjccdiy3qbjbhg37ldr4y7nm5wv6q) with the new signer (f1hhfjedejpwi44wffdqrs3xl6bnygzfjfj3tzpaq). Additionally, please replace the previous GitHub account (laurarenpanda) with the new account (Filedrive-OPS). Thank you.

**Comment by galen-mcandrew** [comment]
Adding signer: https://filfox.info/en/message/bafy2bzaced5ele6lnrnsk3ffj6yr355zc3moz5vn7fgry5fr7lcyqpbo2b4ok?t=4

I will leave the old signer on for now while this clears. If you would like, you can go remove the old signer at your convenience. 

JSON has also been updated to reflect the new f1 address, as well as the new GitHub handle. Thanks!

**Comment by Filedrive-ops** [comment]
Hey @galen-mcandrew

@kacperzuk-neti mentioned in [https://github.com/fidlabs/allocator-tooling/issues/75](https://github.com/filecoin-project/Allocator-Registry/issues/url) that he has opened a PR with a fix, which needs to be merged by someone from the governance team. I'm not sure if you're the right person for this support. If not, could you please help escalate ? thanks.

**Comment by OpenGate01** [comment]
The 500T datacap has been triggered, however, we are encountering bugs when proposing the dc to the client address      [.](https://github.com/OpenGate01/Allocator-Pathway-OpenGate01/issues/14)

**Comment by OpenGate01** [comment]
The 500T datacap has been triggered, however, we are encountering bugs when proposing the dc to the client address.https://github.com/OpenGate01/Allocator-Pathway-OpenGate01/issues/14

**Comment by kacperzuk-neti** [comment]
> The 500T datacap has been triggered, however, we are encountering bugs when proposing the dc to the client address.[OpenGate01/Allocator-Pathway-OpenGate01#14](https://github.com/OpenGate01/Allocator-Pathway-OpenGate01/issues/14)

Please open an issue in allocator-tooling repo describing what bugs you've encountered: https://github.com/fidlabs/allocator-tooling/issues/new
