### ISSUE TITLE
LendMi - Change Github User

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/Allocator-Registry#17]
JSON: https://github.com/filecoin-project/Allocator-Registry/blob/ac8ecca283f6b9be091cf84ecabfb6e46f57cae0/Allocators/1014.json#L4

Change Request:
Remove 
<img width="154" alt="image" src="https://github.com/filecoin-project/Allocator-Registry/assets/94004586/d45e5a64-40ca-4611-a8fa-502aa55233bf">

Add Github account to LendMi

**Comment by LendMi** [comment]
Hello @Kevin-FF-USA , we would like to change to this account, thank you.😀

**Comment by galen-mcandrew** [comment]
Resolved in pull #30
