### ISSUE TITLE
[Allocator #1035] The f1 address is out of date, please update to the Ledger address

### ISSUE THREAD

**Issue by VenusOfficial** [filecoin-project/Allocator-Registry#18]
**Allocator Pathway Number:** 
[1035](https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1035.json)

**Allocator Pathway Name:** 
VFDA

**Change Request:**
After "allocator.tech" connecting to my Ledger, there is no the right address in the available address list.
![image](https://github.com/filecoin-project/Allocator-Registry/assets/155081686/2c4b5161-4cd4-4ee7-832b-c2af76550ba7)

**Comment by Joss-Hua** [comment]
![image](https://github.com/filecoin-project/Allocator-Registry/assets/75723122/31f1aabb-66df-40c9-aba6-d0382550ce05)
My allocator address is not displayed in the list, so the final step of "sign" cannot be completed.
Is this related to this issue? How to solve it?

**Comment by VenusOfficial** [comment]
![image](https://github.com/filecoin-project/Allocator-Registry/assets/155081686/18120663-f7e4-463d-a637-0f58e08fb971)

My allocator address is not displayed in the list, so the final step of "sign" cannot be completed.
Is this related to this issue? How to solve it?

**Comment by VenusOfficial** [comment]
![image](https://github.com/filecoin-project/Allocator-Registry/assets/155081686/b91da11f-5dc2-4c0b-a9fe-3f368bafff88)

My allocator address is not displayed in the list, so the final step of "sign" cannot be completed.
Is this related to this issue? How to solve it?

**Comment by Joss-Hua** [comment]
CC @willscott @Kevin-FF-USA

**Comment by VenusOfficial** [comment]
CC @willscott @Kevin-FF-USA

**Comment by Kevin-FF-USA** [comment]
Hi @VenusOfficial ,

Thanks for the ticket and screenshots (very helpful).
Looking into this now,  will update on backend or reach out if additional information is needed

**Comment by galen-mcandrew** [comment]
Associated org addresses do not have to match the address on the msig (which holds the DataCap) or the msig signers. The associated address is for referencing previous or other org-level accounts.

It sounds like the address that is on your ledger is correctly listed as a signer in the msig. If that is the case, you should be able to use the tooling and construct messages through address f1mkeafrmvg3tiuugtcwpyumjbuyeoey3t2exa4ba to the msig f2hxivxs3we5afsuyx32lwwn44evopz7yea2fsmhy for awarding DataCap. 

Confirming that f1...4ba is a signer on the f2 msig: https://filfox.info/en/address/f2hxivxs3we5afsuyx32lwwn44evopz7yea2fsmhy

**Comment by galen-mcandrew** [comment]
If the right address is listed in the json, but you are not seeing that address in the tooling, it may be resolved from a recent fix. You can now scroll through more ledger addresses in the front-end.

Can you verify if this resolves your problem?
