### ISSUE TITLE
Not able to approve application to my Allocator

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/Allocator-Registry#20]
Hello, team,

context: https://filecoinproject.slack.com/archives/C06MTBZ44P2/p1711676134260609

After the [PR](https://github.com/filecoin-project/Allocator-Registry/pull/15) here, allocator.tech UI still not allowing me to approve an [application](https://github.com/py-guazi/GZ-FIP0078-Pathway/issues/3) somehow? Could someone please help take a look? Thank you!

![image](https://github.com/filecoin-project/Allocator-Registry/assets/1591330/c3679e74-0bb3-44e4-b74e-ea147f238dd7)

**Comment by Fatman13** [comment]
CC @willscott

**Comment by Fatman13** [comment]
Any progress on this one?

**Comment by willscott** [comment]
sorry for missing this on the previous PR. the relevant field is https://github.com/filecoin-project/Allocator-Registry/pull/15/files#diff-322cbbdc6bf0bbd135b89779e966c5f2bcda9b01546450de00e5c379e07b7da7L28 - not 'point of contact' but rather 'github_handles' - can we change that one to match capitalization?

**Comment by Fatman13** [comment]
Ahhh okay got it. Thanks.

**Comment by Kevin-FF-USA** [comment]
Hi @Fatman13,

Friendly check in - did this github change solve the issue --- or anything else needed from our side?

**Comment by Fatman13** [comment]
waiting on the [PR linked](https://github.com/filecoin-project/Allocator-Registry/pull/24) to be merged to see if it is resolved.
