### ISSUE TITLE
Community Diligence Review for Guazi Dynamic allocator 

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/Allocator-Registry#217]
### Type of Allocator

Manual

### Allocator Pathway Name

Guazi Dynamic

### Organization Name

Guazi Dynamic

### Please provide the url to your Allocator Application

https://github.com/filecoin-project/notary-governance/issues/1023

### The Application number linked to your organization

https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1023.json

### Account Authorization

Yes

### How many Datacap refill requests have already been submitted for this pathway

0

### 1st Refresh - How much DataCap did you receive in this refresh application

None

### 2nd Refresh - How much DataCap did you receive in this refresh application

None

### 3rd Refresh - How much DataCap did you receive in this refresh application

None

### Please confirm that you understand that in addition to submitting this Github issue, you will be receiving a diligence review that will require you return to this issue to provide update clarification.

(Yes)

### Please confirm that you have maintained the standards set forward in your application for each dispursment issued to clients and you understand the Fil+ guidelines and your role as an Allocator.

(Yes)

**Comment by Kevin-FF-USA** [comment]
Tracking this in: https://github.com/filecoin-project/Allocator-Governance/issues/196
