### ISSUE TITLE
Community Diligence Review for Dcent - NC allocator

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/Allocator-Registry#220]
### Type of Allocator

Manual

### Allocator Pathway Name

Dcent - NC data

### Organization Name

Dcent

### Please provide the url to your Allocator Application

https://github.com/cryptowhizzard/Fil-A-2

### The Application number linked to your organization

1058

### Account Authorization

Yes

### How many Datacap refill requests have already been submitted for this pathway

1

### 1st Refresh - Please provide the url to your first application for DataCap refresh (submit for all that apply) (If this is the first, leave blank)

https://github.com/filecoin-project/Allocator-Governance/issues/18

### 1st Refresh - How much DataCap did you receive in this refresh application

10 Pib

### 1st Refresh - What compliance guidance were given to this pathway?

Based on a further diligence review, this allocator pathway is in compliance with their application

### 2nd Refresh - How much DataCap did you receive in this refresh application

None

### 3rd Refresh - How much DataCap did you receive in this refresh application

None

### Please confirm that you understand that in addition to submitting this Github issue, you will be receiving a diligence review that will require you return to this issue to provide update clarification.

(Yes)

### Please confirm that you have maintained the standards set forward in your application for each dispursment issued to clients and you understand the Fil+ guidelines and your role as an Allocator.

(Yes)

**Comment by Kevin-FF-USA** [comment]
Closing (Duplicate from Governance Repo)
