### ISSUE TITLE
[Allocator #1015] Unrecognized , Update a new Leger address

### ISSUE THREAD

**Issue by Bitengine-reeta** [filecoin-project/Allocator-Registry#25]
Allocator Pathway Number:
[1015](https://github.com/filecoin-project/notary-governance/issues/1015)

Allocator Pathway Name:
Bitengine Reeta FIL+

Change Request:
The unrecognized Leger address needs to be updated to a new Leger address, and then a new multi-signature address is created for the new Leger address.
- Old leger address: 
f15x23zuhctuqz77tvkzthow3xkpvn3q4kjgxpgya
- New leger address: 
f1km6utrorrtqh572e3ybfu7jq2gfktkgfghscr6i
- New Multi-Address:
f2jh575hxrtfjl7uvu5ymfzrpfyq45fnhvhlajjdi

![image](https://github.com/filecoin-project/Allocator-Registry/assets/116777794/a4031e18-d40b-48b7-a2dc-9043494bfa04)
![Dy98vETIdn](https://github.com/filecoin-project/Allocator-Registry/assets/116777794/a7cb1180-9b50-40fe-bb8e-ce5eff51e8cd)

**Comment by Bitengine-reeta** [comment]
@willscott @galen-mcandrew @Kevin-FF-USA

**Comment by Kevin-FF-USA** [comment]
Hi @Bitengine-reeta ,

Thanks for submitting this ticket.  Wanted to let you know it was received and being worked.  Will echo back shortly when completed (or additional information is needed)

Warmly,
-Kevin

**Comment by Bitengine-reeta** [comment]
@Kevin-FF-USA  Thanks a lot!

**Comment by Bitengine-reeta** [comment]
@galen-mcandrew @Kevin-FF-USA @willscott @jbenet Any update?

**Comment by galen-mcandrew** [comment]
The associated address is not related to signing DataCap through your pathway, it is used to reference org-level addresses that may be managing multiple pathways.

It sounds like you are requesting a new multisig, but that would require the Root Key Holders removing the DataCap and issuing to a new f2. The f2 address was created by your team, and provided to the GovTeam and RKH, so we do not have the ability to add other signers to that msig.

This address (f2p2yz6iv33uiz6snsbgheuvwa4cjclcpi46fpbkq) has 1 signer (
f15x23zuhctuqz77tvkzthow3xkpvn3q4kjgxpgya) and 5PiB of DataCap. You should add your ledger address to this f2 msig, and then we can update the json to include that address.

**Comment by Bitengine-reeta** [comment]
> The associated address is not related to signing DataCap through your pathway, it is used to reference org-level addresses that may be managing multiple pathways.
> 
> It sounds like you are requesting a new multisig, but that would require the Root Key Holders removing the DataCap and issuing to a new f2. The f2 address was created by your team, and provided to the GovTeam and RKH, so we do not have the ability to add other signers to that msig.
> 
> This address (f2p2yz6iv33uiz6snsbgheuvwa4cjclcpi46fpbkq) has 1 signer ( f15x23zuhctuqz77tvkzthow3xkpvn3q4kjgxpgya) and 5PiB of DataCap. You should add your ledger address to this f2 msig, and then we can update the json to include that address.

@galen-mcandrew 
The problem now is that I have the f2p2yz6iv33uiz6snsbgheuvwa4cjclcpi46fpbkq address, but I cannot add any other address to the  Multi-Address f2p2yz6iv33uiz6snsbgheuvwa4cjclcpi46fpbkq, because the a address is only recognized in Leger Live, not in Glif nor https://allocator.tech/.
So, I need to completely replace it with a new f2 address. The 5PiB DataCap on the previous f2 address can never be used, so it can be destroyed or recycled.

**Comment by Bitengine-reeta** [comment]
![image](https://github.com/filecoin-project/Allocator-Registry/assets/116777794/771e4779-8388-4134-96af-7190df437317)

**Comment by Bitengine-reeta** [comment]
1. The f1 address I submitted (f15x23zuhctuqz77tvkzthow3xkpvn3q4kjgxpgya) can only be recognized on Leger Live
2. The current multi-signature address (f2p2yz6iv33uiz6snsbgheuvwa4cjclcpi46fpbkq) only has 1 signer, and I cannot add new members to the multi-signature address through Leger Live.
3. Other platforms cannot recognize this address. I have tried many methods, but it seems that this non-"Third-Party" address cannot be read on third-party platforms.
4. The current solution (ONLY) is to destroy the previous f2 address and update the new f2 address.

**Comment by Bitengine-reeta** [comment]
@galen-mcandrew @Kevin-FF-USA @willscott @jbenet @GovTeam @RKH

**Comment by Bitengine-reeta** [comment]
![image](https://github.com/filecoin-project/Allocator-Registry/assets/116777794/02c449ec-cf7f-4e3b-9e50-a2015b3fc88a)
No matter it is lotus or Glif wallet or https://allocator.tech/, they will not give me the option of derivation mode: bip44 xpub
This is why my address is not recognized.

**Comment by Bitengine-reeta** [comment]
@galen-mcandrew @Kevin-FF-USA 
any new progress?
Is there a huge obstacle to replacing a new multisig address?

**Comment by galen-mcandrew** [comment]
The obstacle requires RKH updates, along with changing json and back-end tracking. This is why we asked allocators to set up their own addresses, so that they could manage those addresses. As an alternative, we set up msig's with a governance team admin signer, so that we could make address changes. Either of those pathways would not require 4 messages from root key holders to update a single allocator. 

It sounds like there is an msig that you created (f2p2yz6iv33uiz6snsbgheuvwa4cjclcpi46fpbkq) with one signer (
f15x23zuhctuqz77tvkzthow3xkpvn3q4kjgxpgya) which you hold the private keys to.

**You can use Lotus to add a new signer to your msig.**

`lotus msig add-propose [command options] [multisigAddress signer]`

**Comment by Bitengine-reeta** [comment]
@galen-mcandrew 
I have tried all methods of adding a new signer (including lotus wallet commands), but none of them can achieve my goal. 
If you have a way to achieve your goal, I can send you my Leger mnemonic phrase via email.

**Comment by Bitengine-reeta** [comment]
@galen-mcandrew @Kevin-FF-USA @willscott 
Already solved.

There is a code problem in https://allocator.tech/ that prevents my address from being recognized. The specific situation is as follows:
https://github.com/filecoin-project/filplus-registry/blob/develop/src/lib/wallet/BaseWallet.ts
![img_v3_02ba_a220189a-a551-4b11-bbd3-354a153ad33g](https://github.com/filecoin-project/Allocator-Registry/assets/116777794/0359d401-17a9-491e-8197-e947b6fe901c)

The first '0' means accountType=0, but my accountType=1
```
protected getBIP44Path-1(index: number): string {
    return `m/44'/${this.lotusNode.code}'/1'/0/${index}
  }

```
