### ISSUE TITLE
[Allocator #1031] Confirmation of Allocator Information

### ISSUE THREAD

**Issue by METAVERSEDATAMINING** [filecoin-project/Allocator-Registry#27]
Allocator Pathway Number:
1031
Allocator Pathway Name:
METAVERSEDATAMINING
Change Request:
My allocator information is not here "https://github.com/filecoin-project/Allocator-Registry/tree/main/Allocators"
Please help to confirme it. Additionally, here is my bookkeeping link: https://github.com/METAVERSEDATAMINING/Allocator-Pathway-MDM.

**Comment by Kevin-FF-USA** [comment]
Hi @METAVERSEDATAMINING,
Wanted to let you know we are working this. 
- Get your organization setup with a JSON tracker
- Get your bookkeeping repo seutp

**Comment by METAVERSEDATAMINING** [comment]
Hi@Kevin-FF-USA 
I'm wondering if there's been any headway on this matter. 
Is there anything I can provide to expedite the resolution process? Please let me know.

> * Get your organization setup with a JSON tracker
> * Get your bookkeeping repo seutp

**Comment by Kevin-FF-USA** [comment]
Hi @METAVERSEDATAMINING 
Apologies for the delays; - its coming from a problem with the JSON file that contains all of the organization deals. Escalating this to a P0 for immediate outside support to get this figured out.

**Comment by METAVERSEDATAMINING** [comment]
I am encouraged by the responses received so far. 
If you could promptly inform me of any further developments or clearly specify what I need to do to make improvements, I would be very grateful.

**Comment by galen-mcandrew** [comment]
PR merged now, JSON created

https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1031.json
