### ISSUE TITLE
[Allocator #1076] Change allocation_bookkeeping

### ISSUE THREAD

**Issue by taft-bitmain** [filecoin-project/Allocator-Registry#29]
Allocator Pathway Number:
1076
Allocator Pathway Name:
Bitmain USA
Change Request:
Change allocation_bookkeeping

new allocation_bookkeeping: https://github.com/filecoin-bitmain/file

**Comment by Kevin-FF-USA** [comment]
Thanks @taft-chen 
You should see the updated Bookkeeping plan now.
