### ISSUE TITLE
Unable to sign dataCap 

### ISSUE THREAD

**Issue by spaceT9** [filecoin-project/Allocator-Registry#33]
https://allocator.tech/application/StorSwift-team/fil-allocator-bookkeeping/f1fmcgclzh7m7pmi3i7qgz3ujpsv5ml5uhhpjeogy

Unable to sign the above issue, error occurred as below:
![305fcdaee19d27d7cc0c2e6c0d7fbb8](https://github.com/filecoin-project/Allocator-Registry/assets/130682426/5680b1d1-8b69-41ce-b4fb-82a85e25e4d9)

please advise and support!

**Comment by Kevin-FF-USA** [comment]
Hi @spaceT9,

Is this issue still persisting for you?
Cc @willscott

**Comment by spaceT9** [comment]
Yes

**Comment by Kevin-FF-USA** [comment]
Hey @spaceT9,
Just wanted to check in.  Filed a ticket directly with the FIDL team. Rockstars who are running the development for the Allocator.tech page, they should have a solution for you

**Comment by spaceT9** [comment]
Thanks, great to know that.

**Comment by spaceT9** [comment]
Is this issue fixed?

**Comment by spaceT9** [comment]
It's two weeks

**Comment by spaceT9** [comment]
It's two weeks

**Comment by galen-mcandrew** [comment]
@spaceT9 FIDL team posted an update with some next steps. 

https://github.com/fidlabs/allocator-tooling/issues/48#issuecomment-2153379440
