### ISSUE TITLE
Pathway Address Modification

### ISSUE THREAD

**Issue by amiclan666** [filecoin-project/Allocator-Registry#34]
### Organization

SSDMINER CLOUD INTELLIGENT

### Applicaiton Number

1017

### Would you like to

Add or Remove a Signer

### New address

f1i2znbisevlalmctotghgnroprplkioss73ka24i

### Do you need Foundation Governance support to create the Multisig?

None

### Is the Github Account used to file this request is already recorded on the Allocator JSON for your organization?

Yes

**Comment by galen-mcandrew** [comment]
Address added as signer in JSON file, merge request closed.

**Comment by amiclan666** [comment]
@galen-mcandrew Hello, could you use the wallet f1a5b5cn5xgsmui2kivzj2eryzrqmhmew4tytj3by to help us add f1i2znbisevlalmctotghgnroprplkioss73ka24i to the multisig wallet f2ddjxnv4bvvl6br7nuuthgk6cx5ad53jnqefszka because we accidentally lost the relevant wallet

**Comment by Kevin-FF-USA** [comment]
To confirm - you no longer have access to original ledger?

**Comment by Kevin-FF-USA** [comment]
"pathway_addresses": {
    "msig": "f2ddjxnv4bvvl6br7nuuthgk6cx5ad53jnqefszka",
    "signer": [
      "f1a5b5cn5xgsmui2kivzj2eryzrqmhmew4tytj3by",
      "f1gyub4w33xd273hw4n2lii5txpaj64hktqjbb7sa",
      "f1n6m3b3bgqpzd67xmvatjqpaxhepgtoscepigs4y"

**Comment by galen-mcandrew** [comment]
bafy2bzaceacix6r262rio77yrrdwio5psvesocuxt7gcyufh3qxt4xjtmhuj6

Added, updated JSON.
