### ISSUE TITLE
Allocators showing as auto or market based

### ISSUE THREAD

**Issue by kevzak** [filecoin-project/Allocator-Registry#36]
Looks like 5 active allocators are showing as automatic or market based in dashboards but I see no way to actually prove they meet this criteria and are likely just manual allocators. 

Gov team should confirm actual allocator activity and type and remove allocator or update allocator json accordingly.

https://filecoinpulse.pages.dev/allocator/f03011612/

https://filecoinpulse.pages.dev/allocator/f03004870/

https://filecoinpulse.pages.dev/allocator/f03019831/

https://filecoinpulse.pages.dev/allocator/f03018484/

https://filecoinpulse.pages.dev/allocator/f03018314/

**Comment by kevzak** [comment]
@Kevin-FF-USA any way to update the json field for these allocators? They should all say manual. Not being labeled as manual causes issues in dashboards 

example is the Pathway distribution chart here: https://filecoinpulse.pages.dev/allocators/

**Comment by Kevin-FF-USA** [comment]
Hi @kevzak 

JSONs updated for (5)

- IPFSTT: https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1006.json

- TOP POOL: https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1046.json

- VENUS: https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1035.json

- BIG DATA EXCHANGE: https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1027.json

- NIWAN: https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1081.json

**Comment by Kevin-FF-USA** [comment]
Leaving issue open until I modify the legacy documentation to reflect these change in Metapathway stus
