### ISSUE TITLE
Modify information 1038

### ISSUE THREAD

**Issue by stcloudlisa** [filecoin-project/Allocator-Registry#79]
### Organization

Shenzhen SpaceTime Cloud Technology Co., Ltd.

### Applicaiton Number

1038

### Would you like to

Update the url for an existing bookkeping repo

### Updated Bookkeeping URL

https://github.com/stcloudlisa/Allocator-Pathway-Data

### Previous Bookkeeping URL

https://github.com/stcloudlisa

### Is the Github Account used to file this request is already recorded on the Allocator JSON for your organization?

Yes

### Reason for the change

I filled in the wrong information before

### Additional Information

no
```[tasklist]
### Tasks
```

**Comment by stcloudlisa** [comment]
Can anyone help me fix this? Otherwise I can't start it.

**Comment by stcloudlisa** [comment]
我们提到需要修改的json文件为https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1038.json

**Comment by Kevin-FF-USA** [comment]
Hi @stcloudlisa 


Merge submitted. New repository for bookkeeping is active.


I didnt see any previous applications in the old repo that needed to be migrated, but if anything else is needed - please let me know.

**Comment by stcloudlisa** [comment]
![图片](https://github.com/filecoin-project/Allocator-Registry/assets/112812896/efeda937-6487-4ac5-a412-508aa6b96b8b)
After trying to install the bot, I tried to pull the file into the library and it appeared to be an error. Sorry to bother you again. @Kevin-FF-USA
