### ISSUE TITLE
Modify information 1003

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/Allocator-Registry#8]
Can you help me correct this repository address? I made a mistake when submitting the information.
In https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1003.json,
change "allocation_bookkeeping": "https://github.com/FroghubMan" to https://github.com/FroghubMan/filplus."

**Comment by galen-mcandrew** [comment]
Updated, closing issue
