### ISSUE TITLE
Pathway Address Modification

### ISSUE THREAD

**Issue by amiclan666** [filecoin-project/Allocator-Registry#80]
### Organization

SSDMINER CLOUD INTELLIGENT

### Applicaiton Number

1017

### Would you like to

Other

### New address

f1i2znbisevlalmctotghgnroprplkioss73ka24i

### Do you need Foundation Governance support to create the Multisig?

None

### Is the Github Account used to file this request is already recorded on the Allocator JSON for your organization?

Yes

### Additional Information

Due to the unexpected loss of our Ledger wallet, we have lost control of the multi-signature wallet. We hope the official team can use f1a5b5cn5xgsmui2kivzj2eryzrqmhmew4tytj3by to help us add the aforementioned new hardware wallet address to the multi-signature wallet.

**Comment by amiclan666** [comment]
@Kevin-FF-USA We greatly need your help.

**Comment by Kevin-FF-USA** [comment]
Hi @amiclan666,

Thanks for the patience while we sorted this out.  So there were (3) addresses already tied to this Allocator account.  If the ledger was lost, I went ahead and removed the old signing addresses.

"f1gyub4w33xd273hw4n2lii5txpaj64hktqjbb7sa",
"f1i2znbisevlalmctotghgnroprplkioss73ka24i",
 "f1n6m3b3bgqpzd67xmvatjqpaxhepgtoscepigs4y
 
 Please let me know if this new address is working correctly for you now.
 
 f1i2znbisevlalmctotghgnroprplkioss73ka24i

**Comment by amiclan666** [comment]
Hello @Kevin-FF-USA,

Due to the loss of our Ledger device, we have lost control of the two associated multi-signature wallets `f1gyub4w33xd273hw4n2lii5txpaj64hktqjbb7sa` and `f1n6m3b3bgqpzd67xmvatjqpaxhepgtoscepigs4y`, and they can be removed.

We have purchased a new Ledger device and generated a new wallet: `f1i2znbisevlalmctotghgnroprplkioss73ka24i`, which is currently operating normally. We request that you add this new wallet to the multi-signature account using the account that created the multi-signature wallet: `f1a5b5cn5xgsmui2kivzj2eryzrqmhmew4tytj3by`. This is crucial for us to proceed with the Allocator's work. Thank you very much.

**Comment by amiclan666** [comment]
@Kevin-FF-USA 
The new address `f1i2znbisevlalmctotghgnroprplkioss73ka24i` is now working correctly. Could you please help us update it?
Thank you!
