### ISSUE TITLE
Change old signer address to ledger address

### ISSUE THREAD

**Issue by Davisson2025** [filecoin-project/Allocator-Registry#82]
### Organization

ANTPOOL

### Applicaiton Number

1088

### Would you like to

Change an existing Multisig Address

### Previous address

f1acun2mgluaau5nx4ixbzwyo422k3i2ghkptqaoy

### New address

f1ylwkezohcn7ggbkids25xqu5yudllsqg6pyhmii

### Do you need Foundation Governance support to create the Multisig?

None

### Is the Github Account used to file this request is already recorded on the Allocator JSON for your organization?

Yes

### Additional Information

we need update old signer address to the ledger address.

**Comment by Davisson2025** [comment]
@Kevin-FF-USA Kevin, we need your help.

**Comment by Kevin-FF-USA** [comment]
Hi @Davisson2025,
Processed the updates to organization,  please let me know if there are any issues.  Happy to help.

**Comment by Davisson2025** [comment]
Hi, @Kevin-FF-USA 

We recently discovered a problem while preparing for approval datacap.

Only the github configuration file has been changed, and the signature address on the chain has not changed.

<img width="484" alt="32898a64c5f108837f57c75cbbeffe7" src="https://github.com/user-attachments/assets/608d0b52-3acc-434f-963b-0063f216f27f">

So can you help us modify the address on the chain, tks.

**Comment by Davisson2025** [comment]
Hi, @Kevin - FF ***@***.***>

We recently discovered a problem while preparing for approval datacap.

Only the github configuration file has been changed, and the signature
address on the chain has not changed.
[image: 32898a64c5f108837f57c75cbbeffe7]
<https://private-user-images.githubusercontent.com/157135365/352533495-608d0b52-3acc-434f-963b-0063f216f27f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTgxNzQsIm5iZiI6MTcyMTk5Nzg3NCwicGF0aCI6Ii8xNTcxMzUzNjUvMzUyNTMzNDk1LTYwOGQwYjUyLTNhY2MtNDM0Zi05NjNiLTAwNjNmMjE2ZjI3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQxMjQ0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjU2NDYwNDUyZDYyN2M0MjA5OWU2Zjg4YjZjNGQyZmJiNTMyMTNlN2EzZGJiMjZkMGI5YjcxOGRkZTczN2JkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lj0TOwF2PAoylkqMtg4MmIAeU1Bt2mc6_L9csA-iOYc>

So can you help us modify the address on the chain, tks.


https://github.com/filecoin-project/Allocator-Registry/issues/82

**Comment by galen-mcandrew** [comment]
Requesting updates to [f2yz73r5qvr257jpifsdxyinpfnkhnyzl6p2qot2q](https://filfox.info/en/address/f03019944) to include f1ylwkezohcn7ggbkids25xqu5yudllsqg6pyhmii

Admin message receipt: https://filfox.info/en/message/bafy2bzaced7vivbcqkxso32g23523u6wktjnirdx46ktcszihv54cj64nur6m

@Davisson2025 this should be completed now, thanks!
