### ISSUE TITLE
Update bookkeeping URL

### ISSUE THREAD

**Issue by ipfsforcezuofu** [filecoin-project/Allocator-Registry#83]
### Organization

IPFSForce

### Applicaiton Number

1034

### Would you like to

Update the url for an existing bookkeping repo

### Updated Bookkeeping URL

https://github.com/ipfsforcezuofu/ipfsforce-allocator

### Previous Bookkeeping URL

https://github.com/ipfs-force-community/allocator

### Is the Github Account used to file this request is already recorded on the Allocator JSON for your organization?

Yes

### Reason for the change

To avoid the risk of security to share the previous bookkeeping URL to public.

**Comment by Kevin-FF-USA** [comment]
Hi @ipfsforcezuofu,

Bookeeping url has been updated.   I did not migrate any previous records from the old bookkeeping. Please let me know if there are any issues.
