### ISSUE TITLE
TopBlocks want to change Bookkeep URL and also Repo transfer 

### ISSUE THREAD

**Issue by woshidama323** [filecoin-project/Allocator-Registry#84]
### Organization

TopBlocks

### Applicaiton Number

1069

### Would you like to

Update the url for an existing bookkeping repo

### Updated Bookkeeping URL

https://github.com/TopBlocks/TopBlocks_Allocator

### Previous Bookkeeping URL

https://github.com/filplus-bookkeeping/TopBlocks

### Is the Github Account used to file this request is already recorded on the Allocator JSON for your organization?

Yes

### Reason for the change

filplus-bookkeeping has no enough permission for handling

**Comment by woshidama323** [comment]
Also want to change path-way address to an new ledger one
[reason is here](https://github.com/filecoin-project/Allocator-Governance/issues/6#issuecomment-2177421534)
Thanks

**Comment by Kevin-FF-USA** [comment]
Hi @woshidama323 

JSON file for pathway and bookkeeping have been updated.
I'll see if possible to migrate the previous bookkeeping issues to your new repo

**Comment by Kevin-FF-USA** [comment]
Closing this issue out - but if any problems or needs please let me know.
