### ISSUE TITLE
TopBlocks request Pathway Address Modification

### ISSUE THREAD

**Issue by woshidama323** [filecoin-project/Allocator-Registry#85]
### Organization

TopBlocks

### Applicaiton Number

1069

### Would you like to

Add or Remove a Signer

### Previous address

f13scefkwue5cpivykug4qod4tkcmuqf4bgu7yzsy

### New address

f1ez4nfx4lbqmddefk3gpqisf2xcfr3g6qm4qes7i

### Do you need Foundation Governance support to create the Multisig?

Yes

### Is the Github Account used to file this request is already recorded on the Allocator JSON for your organization?

Yes

**Comment by Kevin-FF-USA** [comment]
Hi @woshidama323,

Just wanted to send a friendly check in.
JSON updated to reflect these new address.  As a final close out, now verifying the multisig and this will be set to start.

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/message/bafy2bzacebp6jn4fcvjhmyhowb5mh3wknwwludfboib5tyrhe2wrir4ldfo7u?t=4

Adding signer to msig.
