### ISSUE TITLE
Modify information 1038

### ISSUE THREAD

**Issue by stcloudlisa** [filecoin-project/Allocator-Registry#9]
We fil the allocation_bookkeeping": "https://github.com/stcloudlisa", This is wrong.
I need to change the address to "https://github.com/stcloudlisa/Allocator-Pathway-Data".
Thanks

**Comment by Kevin-FF-USA** [comment]
Hi @stcloudlisa 
Thanks for the ticket.  Wanted to let you know the address has been changed to reflect.  Please let us know if anything else is needed.
![image](https://github.com/filecoin-project/Allocator-Registry/assets/94004586/31e523fb-b9c8-4a2f-bacc-5e19ef220d47)

**Comment by stcloudlisa** [comment]
It seems that you forgot to save your modifications, so it is still https://github.com/stcloudlisa. Fortunately, you can help me modify it again. Thank you.

**Comment by stcloudlisa** [comment]
@Kevin-FF-USA we need your help

<img width="613" alt="WX20240329-175402@2x" src="https://github.com/filecoin-project/Allocator-Registry/assets/112812896/1197b635-4b17-4ead-b3a3-9c67069210c2">

**Comment by stcloudlisa** [comment]
@Kevin-FF-USA does any upate？
