### ISSUE TITLE
Request to modify pathway address of MinerDAO

### ISSUE THREAD

**Issue by maxvint** [filecoin-project/Allocator-Registry#97]
### Organization

MinerDAO

### Applicaiton Number

1065

### Would you like to

Change an existing Multisig Address

### Previous address

f2uib6cqjmos6ir4ajx4aqt4pbglrrsd7w6ubovki

### New address

f2gelosrtlc7iciehlytdrz2dqsakgadtuclp4eli

### Do you need Foundation Governance support to create the Multisig?

None

### Is the Github Account used to file this request is already recorded on the Allocator JSON for your organization?

Yes

### Additional Information

PR: https://github.com/filecoin-project/Allocator-Registry/pull/93

**Comment by Kevin-FF-USA** [comment]
https://github.com/filecoin-project/Allocator-Registry/pull/93
